In [ ]:
import cv2
import numpy as np

img  = cv2.imread('apple.jpeg', cv2.IMREAD_GRAYSCALE)

# kernel = np.array([[1,1,1],[1,-8,1],[1,1,1]])         #Identity
# kernel = np.array([[0,0,0],[0,1,0],[0,0,0]])          #Ridge or edge detection
# kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]])      #Ridge or edge detection
kernel = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])  #Sharpen
# kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])      #Box blur(normalized)
# kernel = np.array([[1,1,1],
#                    [1,1,1],
#                    [1,1,1]], dtype=float)
# kernel = kernel * (1/9)                               #Gaussian blur 3x3(approximation)

# kernel = np.array([[1,2,1],
#                    [2,4,2],
#                    [1,2,1]], dtype=float)
# kernel = kernel * (1/16)

# kernel = np.array([[1,4,6,4,1],                         #Gaussian blur 5x5(approximation)
#                    [4,16,24,16,4],
#                    [6,24,36,24,6],
#                    [4,16,24,16,4],
#                    [1,4,6,4,1]], dtype=float)
# kernel = kernel * (1/256)



print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge',output)
cv2.waitKey(0)

[[-1 -1 -1]
 [-1  8 -1]
 [-1 -1 -1]]


27

: 